#ifdef AUTOCONNECT_MENULABEL_HOME
#undef AUTOCONNECT_MENULABEL_HOME
#define AUTOCONNECT_MENULABEL_HOME "Thermostat"
#endif

#ifdef AUTOCONNECT_MENULABEL_RESET
#undef AUTOCONNECT_MENULABEL_RESET
#define AUTOCONNECT_MENULABEL_RESET "Restart"
#endif
